const KEY='miBebeData_v1';
const baby={name:'Liam', birth:'2026-06-09'};
let data=JSON.parse(localStorage.getItem(KEY)||'{"records":[],"photo":""}');
const $=s=>document.querySelector(s);
const save=()=>{localStorage.setItem(KEY,JSON.stringify(data)); render();};
const fmtTime=t=>new Date(t).toLocaleTimeString('es-US',{hour:'numeric',minute:'2-digit'});
const today=()=>new Date().toISOString().slice(0,10);
function ageText(){const b=new Date(baby.birth+'T12:00:00'), n=new Date(); let m=(n.getFullYear()-b.getFullYear())*12+n.getMonth()-b.getMonth(); let d=n.getDate()-b.getDate(); if(d<0){m--; const prev=new Date(n.getFullYear(),n.getMonth(),0).getDate(); d+=prev;} return `${m} ${m===1?'mes':'meses'} y ${d} ${d===1?'día':'días'}`}
function render(){
 $('#babyAge').textContent=ageText(); const n=new Date(); $('#todayLabel').textContent=n.toLocaleDateString('es-US',{weekday:'long',month:'long'}); $('#dayNumber').textContent=n.getDate();
 const r=data.records.filter(x=>x.date===today());
 const f=r.filter(x=>x.type==='feeding'), s=r.filter(x=>x.type==='sleep'), d=r.filter(x=>x.type==='diaper'), g=data.records.filter(x=>x.type==='growth').sort((a,b)=>b.ts-a.ts)[0];
 $('#feedSummary').textContent=f.length?`${f.length} registro${f.length>1?'s':''}`:'Sin registros';
 $('#sleepSummary').textContent=s.length?`${s.length} registro${s.length>1?'s':''}`:'Sin registros'; $('#diaperSummary').textContent=`${d.length} hoy`; $('#weightSummary').textContent=g?`${g.weight} lb`:'Sin registros';
 const recent=[...data.records].sort((a,b)=>b.ts-a.ts).slice(0,8); $('#recentList').innerHTML=recent.length?recent.map(x=>`<div class="record"><div class="record-main"><div class="record-icon">${icon(x.type)}</div><div><strong>${title(x.type)}</strong><br><small>${x.detail} · ${fmtTime(x.ts)}</small></div></div><button class="link" data-delete="${x.id}">Eliminar</button></div>`).join(''):'<div class="empty">Aún no hay registros.<br>Presiona “Registrar actividad” para comenzar.</div>';
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{data.records=data.records.filter(x=>x.id!==b.dataset.delete);save();toast('Registro eliminado');});
 if(data.photo){$('#photoBtn').style.backgroundImage=`url(${data.photo})`;$('#photoBtn').style.backgroundSize='cover';$('#photoBtn').textContent='';}
}
const icon=t=>({feeding:'🍼',sleep:'😴',diaper:'🧷',growth:'⚖️',diary:'📖',activity:'✨'}[t]||'📝');
const title=t=>({feeding:'Alimentación',sleep:'Sueño',diaper:'Pañal',growth:'Peso',diary:'Diario',activity:'Actividad'}[t]||'Registro');
function openModal(kind){let html=''; if(kind==='menu'){html=`<h2>Más</h2><div class="menu"><button data-action="export">📤 Exportar mis registros</button><button data-action="clear">🗑️ Borrar todos los registros</button><button data-action="photo">👶 Cambiar foto de Liam 🩵</button></div>`} else if(kind==='feeding'){html=`<h2>🍼 Alimentación</h2><form class="form" id="form"><label>Tipo<select name="detail"><option>Fórmula</option><option>Leche materna</option><option>Comida</option><option>Otro</option></select></label><label>Cantidad (oz)<input name="amount" type="number" min="0" step="0.5" placeholder="Ej. 2"></label><div class="actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary-btn">Guardar</button></div></form>`} else if(kind==='sleep'){html=`<h2>😴 Sueño</h2><form class="form" id="form"><label>Duración (minutos)<input name="duration" type="number" min="1" placeholder="Ej. 90" required></label><label>Nota<textarea name="note" placeholder="Cómo durmió…"></textarea></label><div class="actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary-btn">Guardar</button></div></form>`} else if(kind==='diaper'){html=`<h2>🧷 Pañal</h2><form class="form" id="form"><label>Tipo<select name="detail"><option>Orina</option><option>Popó</option><option>Orina y popó</option></select></label><div class="actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary-btn">Guardar</button></div></form>`} else if(kind==='growth'){html=`<h2>⚖️ Crecimiento</h2><form class="form"><label>Peso (lb)<input name="weight" type="number" min="0" step="0.1" required></label><label>Estatura (cm)<input name="height" type="number" min="0" step="0.1"></label><div class="actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary-btn">Guardar</button></div></form>`} else if(kind==='diary'){html=`<h2>♡ Diario</h2><form class="form"><label>Escribe una nota<textarea name="note" required placeholder="Un momento especial de Liam 🩵…"></textarea></label><div class="actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary-btn">Guardar</button></div></form>`} else if(kind==='activity'){html=`<h2>✨ Actividad</h2><form class="form"><label>Actividad<input name="detail" required placeholder="Ej. Sonrió, jugó, paseó…"></label><div class="actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary-btn">Guardar</button></div></form>`} else if(kind==='all'){html=`<h2>Todos los registros</h2><div class="list">${[...data.records].sort((a,b)=>b.ts-a.ts).map(x=>`<div class="record"><div><strong>${icon(x.type)} ${title(x.type)}</strong><br><small>${x.detail} · ${new Date(x.ts).toLocaleString('es-US')}</small></div></div>`).join('')||'<div class="empty">No hay registros.</div>'}</div>`}
 $('#modalContent').innerHTML=html; $('#modal').hidden=false;
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal);
 const form=$('#modalContent form'); if(form) form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form);const o=Object.fromEntries(fd);let detail=o.detail||o.note||''; if(kind==='feeding'&&o.amount)detail+=` · ${o.amount} oz`; if(kind==='sleep')detail=`${o.duration} min${o.note?' · '+o.note:''}`; if(kind==='growth')detail=`${o.weight} lb${o.height?' · '+o.height+' cm':''}`; data.records.push({id:crypto.randomUUID(),type:kind,detail,date:today(),ts:Date.now(),weight:o.weight||null});save();closeModal();toast('Guardado correctamente');};
 document.querySelector('[data-action="export"]')?.addEventListener('click',exportData); document.querySelector('[data-action="clear"]')?.addEventListener('click',()=>{if(confirm('¿Borrar todos los registros?')){data.records=[];save();closeModal();toast('Registros borrados')}}); document.querySelector('[data-action="photo"]')?.addEventListener('click',()=>{$('#photoInput').click();closeModal()});
}
function closeModal(){$('#modal').hidden=true} function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),1800)}
function exportData(){const blob=new Blob([JSON.stringify({baby,data},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mi-bebe-registros.json';a.click();URL.revokeObjectURL(a.href);toast('Archivo exportado')}
$('#quickAdd').onclick=()=>openModal('activity'); document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>openModal(x.dataset.open)); $('#viewAll').onclick=()=>openModal('all'); $('#closeModal').onclick=closeModal; $('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));b.classList.add('active');const t=b.dataset.tab;if(t==='activity')openModal('activity');else if(t==='growth')openModal('growth');else if(t==='diary')openModal('diary');else if(t==='more')openModal('menu')});
$('#photoBtn').onclick=()=>$('#photoInput').click(); $('#photoInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{data.photo=rd.result;save();toast('Foto guardada')};rd.readAsDataURL(f)};
render();
